FREQUENCIES = [0, 880*2]
RATE        = 96000
CHUNK_SIZE  = 1024
CHUNKS_PER_BUFFER = 9
BUFFER_SIZE = CHUNK_SIZE * CHUNKS_PER_BUFFER
VOLUME      = 0.4

WARMUP      = 0.1
DURATION    = 2

# use points in fft this far from peak when calculating signal/noise ratio
SUM_DISTANCE_FROM_PEAK = 1

CALIBRATION_SIGNALS   = 16
CALIBRATION_THRESHOLD = 10000
ZEROES_AFTER_CALIBRATION = 4
BIT_THRESHOLD         = 800000
